### ISSUE TITLE
Practicemode finishing

### ISSUE THREAD

**Issue by QaleQ** [hettoo/racesow#20]
When you finish a map in practice mode, is it really necessary that it respawns you? The notification should be enough for people to know where the finishline is and that they passed it. This particularly ruins maps where you TS and intend to start from where the finish is, but i know it's been a bother a few other times aswell. Like if you noclip for 5 min to get to the end, then accidentally finish before you position save and get spawned back to the start, or if you position save quickly when you accidentally trigger the finish, resulting in a spawn on the finishline where you have to get away from it and position save again to not have it loop over and over.

**Comment by hettoo** [comment]
Done.

**Comment by QaleQ** [comment]
Immediately notice how senseless it was to have it there in the first place, feels awesome :) On an unrelated note: H bot should be on all servers IMO. At least until someone complains about it. And then maybe have one "unsurveilled" server, for those special routes that ppl wanna hide for some reason.. Don't you agree?

**Comment by hettoo** [comment]
I do, but some time ago I put it in NL#2, which went fine for some time. Later I also added it to DE#2. Then after a while DE#2 hung again, so I moved it out and some time later the same thing happened to NL#2. So unless someone magically finds out why this happens, I'm not going to expand its presence at all.

If we're talking unrelated things: I'm thinking about having people join the players team automatically after entering the game. This prevents noobs from asking questions about joining and also puts an emphasis on playing rather than spectating. You can just start right away. Defrag has this too. Thoughts?

**Comment by QaleQ** [comment]
I see, it couldn't be related to the server being outdated in some way? Because if so then maybe it's worth trying it again now that things have been updated on all servers? And there must be some way to figure out what's causing it if that's not the case?

I think that sounds like a great idea! Spectating is secondary, so that should be the option the noobs have to look for, if anything, and not how to join :)

**Comment by hettoo** [comment]
Last time I tried they were just updated, so I guess it didn't help in the end.
There are two ways to figure it out. One is to study the entire protocol to see what might be wrong, which takes much time and I may still not see it. The other involves having a server admin compile racesow in debug mode, run it in a debugger, wait for the bug to occur and send me a backtrace. Since it tends to happen with many players only they will all have to be bothered with this.

**Comment by QaleQ** [comment]
Wow, what a hassle :/ Maybe we could find someone to do the debug compile, then ask the other admins to take their servers down temporarily, then all of them don't have to do debug compile.. Plus, we'll get more people on the servers because there would be fewer of them... Or something, idk :>

**Comment by hettoo** [comment]
Only one debugging server is needed in any case. I'm sure mute/iceman wouldn't mind much helping out.
The hassle is more on the player side: "let's play until we crash" and then it may not happen at all for a long time.

**Comment by QaleQ** [comment]
That's true, I was just thinking, since it crashed more often with many people on the server, that it would be overwith faster if we had less servers to choose from during that time. Rarely more than 7-8 people on the same server now a days, even if there are a total of 16-17 people online.

Well, random crashes occur from time to time, people aren't too bothered by it.. Plus, they don't have to know what we're up to xD

**Comment by hettoo** [comment]
Hehe, alright. I'll see if I can organize it some time, but it may have to
wait a while.
Don't really like the idea of having one server only for an indefinite
amount of time, so we'll just put it on one and maybe have to wait for a
while until it happens.
