### ISSUE TITLE
Chase score

### ISSUE THREAD

**Issue by QaleQ** [hettoo/racesow#3]
The "chase score" command often chooses to follow the player with the worst time instead of the player with the best time. Mostly happens when people are named "player" and not being able to beat the current time set by someone using that nick, perhaps related to the rec being old somehow?

**Comment by hettoo** [comment]
I think this happened when the player had a time higher than about 32 seconds, because the code was using the score stat value (used to send data like this to clients) which has a low size and is rather inaccurate.
I've changed it to use the real score now, please close the issue if you can confirm it works as expected now.

**Comment by QaleQ** [comment]
I'll keep an eye out for it, but it's not gonna be easy to be 100% sure :p

**Comment by hettoo** [comment]
I see, pretty sure that was the problem so I'll close it now, just reopen if you notice it again.
